# [LINKTO] ~/.bashrc

#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# alias ls='ls --color=auto'
# PS1='[\u@\h \W]\$ '

export PATH="$PATH:$HOME/dotfiles/bin"
export PATH="$PATH:$HOME/.inst/flutter/bin"
export PATH="$PATH:$HOME/.inst/zig/build/stage3/bin"
export PATH="$PATH:$HOME/.inst/zls"
export PATH="$PATH:$HOME/.inst/simavr/simavr"
export PATH="$PATH:$HOME/.inst/all-appimages"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/bin"

if [ -f `which powerline-daemon` ]; then
  powerline-daemon -q
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1
  . /usr/share/powerline/bindings/bash/powerline.sh
fi

