# [LINKTO] ~/.bashrc

#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# alias ls='ls --color=auto'
PS1="\e[0;36m\\u\e[0;36m@${HOSTNAME:0:2}..${HOSTNAME:0-2}:\e[30;46m\\W\e[0;31m ${SHELL##*/}> \e[0m"

export PATH="$PATH:$HOME/dotfiles/bin"
export PATH="$PATH:$HOME/.inst/flutter/bin"
export PATH="$PATH:$HOME/.inst/zig/build/stage3/bin"
export PATH="$PATH:$HOME/.inst/zls"
export PATH="$PATH:$HOME/.inst/simavr/simavr"
export PATH="$PATH:$HOME/.inst/arduinoide/bin"
export PATH="$PATH:$HOME/.inst/all-appimages"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/wpilib/2023/frccode"
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:$HOME/.config/emacs/bin"
export PATH="$PATH:$HOME/.nimble/bin"

# Stop mouse pointer from being disabled while typing
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Disable While Typing Enabled" 0

#if [ -f `which powerline-daemon` ]; then
#  powerline-daemon -q
#  POWERLINE_BASH_CONTINUATION=1
#  POWERLINE_BASH_SELECT=1
#  . /usr/share/powerline/bindings/bash/powerline.sh
#fi

[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh

source /usr/share/nvm/init-nvm.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

alias scroff="sleep 0.1 && xset -display :0.0 dpms force off"
alias clang_raylib="clang -o rlapp -lraylib -lGL -lm -lpthread -ldl -lrt -lX11"
alias x='(cd $(git rev-parse --show-toplevel); xmake)'

export QSYS_ROOTDIR="/home/landon/intelFPGA_lite/22.1std/quartus/sopc_builder/bin"

source "$HOME/Xilinx_ise/14.7/ISE_DS/settings64.sh" >/dev/null

# Xilinx puts stuff on the PATH that messes everything up, so we have to move it to the end
ORIG_PATH_PRE_XILINX_FIX="$PATH"
PATH=`fix-path-xilinx "$(echo $PATH)"`

# Now we fix the LD_LIBRARY_PATH, thanks a lot Xilinx I mean AMD
# But we have to remember the actual path with the ISE stuff to run ISE
LD_LIBRARY_PATH_POST_XILINX_PRE_FIX="$LD_LIBRARY_PATH"
LD_LIBRARY_PATH=""

# Now we have to undo our fix when actually running ISE
# This will break if there's a space in the path but I don't really want to bother with
# that right now
ISE_BINARY_PATH="$(which ise)"
alias ise="LD_LIBRARY_PATH=$LD_LIBRARY_PATH_POST_XILINX_PRE_FIX $ISE_BINARY_PATH"

