#!/bin/bash

alias c='clear; '
alias gits='git status'
alias hotspot='nmcli con up Hotspot'
alias hcode='code .; exit'
alias gnh='gnvim . & exit'
alias cldn='rm ~/Downloads/*'

# Lets you write stuff like `loop cargo check; done`
alias loop='while :; do sleep 2; clear; '

# THE FOLLOWING ALIASES OVERWRITE EXISTING
# BINARIES ON THE PATH
if [[ "$Y_BASH_NoOverwriteAliases" -ne "1" ]]; then
	alias lorien='lorien & exit'
fi

