#!/bin/bash

(cd ~/dotfiles; git pull --ff-only)
if [[ $1 == '--fwd' ]]; then
	(cd ~/dotfiles/syncconfig; stack exec syncconfig-exe < yes r)
else
	(cd ~/dotfiles/syncconfig; stack exec syncconfig-exe)
fi

