syntax on

filetype plugin indent on

set rtp^="/home/lpc/.opam/4.14.0/share/ocp-indent/vim"

autocmd FileType ocaml source /home/lpc/.opam/4.14.0/share/ocp-indent/vim/indent/ocaml.vim

nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <Esc>:m .+1<CR>==gi
inoremap <C-k> <Esc>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv

