#!/bin/bash

cap=$(cat /sys/class/power_supply/BAT0/capacity)
state=$(cat /sys/class/power_supply/BAT0/status)

if (( "$cap" < "15" ))
then
	echo -n "<fc=#ff0000>$cap%</fc> "
elif (( "$cap" < "30" ))
then
	echo -n "<fc=#ffff00>$cap%</fc> "
elif (( "$cap" < "60" ))
then
	echo -n "$cap% "
else
	echo -n "<fc=#00ff00>$cap%</fc> "
fi

if [[ "$state" == "Charging" ]]
then
	echo "(C)"
elif [[ "$state" == "Discharging" ]]
then
	echo "(D)"
elif [[ "$state" == "Not charging" ]]
then
	echo "(B)"
else
	echo "(U)"
fi
